---
- name: restart ldap client
  service:
    name: nslcd
    state: restarted
  notify: stop nscd cache

- name: stop nscd cache
  service:
    name: nscd
    state: stopped

- name: rebuild FreeBSD pwdb 
  command: /usr/sbin/pwd_mkdb /etc/master.passwd

- name: rebuild login.conf database
  command: /usr/bin/cap_mkdb /etc/login.conf
